set-option -g default-shell /usr/bin/zsh
set-option -g prefix C-q
set-window-option -g mode-keys vi
unbind-key C-b
bind-key C-q send-prefix

bind-key j select-pane -D
bind-key h select-pane -L
bind-key k select-pane -U
bind-key l select-pane -R
bind-key K swap-pane -U
bind-key J swap-pane -D
# interface
#------------
# pane
#------------
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on
set -g pane-border-fg black
set -g pane-active-border-fg blue
bind-key { swap-window -t -1
bind-key } swap-window -t +1

bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

bind-key X kill-pane
#------------
# status bar
#------------
set-option -g status-position top
source '/home/yifan/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf'

