github.pie.apple.com:
    oauth_token: c844a0f8bb109a338c19a508cb466ef42e3c9d30
    user: yifange
    git_protocol: https
    users:
        yifange:
            oauth_token: c844a0f8bb109a338c19a508cb466ef42e3c9d30
